# Site settings
name: Make it True
email: woyouwole_2012@outlook.com
author: ShiZhong
url: http://woyouwole2012.github.io
resume_site: http://woyouwole2012.github.io
github: https://github.com/woyouwole2012
baseurl: 
description: Almost, nothing is impossible!
meta_description: 石钟;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: Knowledge is power , Time is money .
banner: 生气，是拿别人的错误惩罚自己。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: woyouwole2012

# Build settings
markdown: kramdown

baidu_analysis: c51e83e31dffebdef80eb3f2810785d5

