# Site settings
name: Make it True
email: woyouwole_2012@outlook.com
author: ShiZhong
url: http://www.github.woyouwole2012
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/woyouwole2012/
baseurl: 
description: Actually, less is more!
meta_description: 石钟;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: woyouwole2012

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

